Update README to use curl instead of wget
wget on CentOS 6 returns this error:

ERROR: certificate common name “*.a.ssl.fastly.net” doesn’t match
requested host name “raw.github.com”.

This makes it difficult to get started with all of the SSH keys.  This
patch updates the README to use curl which does work with Github's SSL
certificate.